version: '3'
services:
  orbital-sync:
    image: ghcr.io/mattwebbio/orbital-sync:latest
    hostname: "pi501.wagsworld.com"
    extra_hosts:
      - "pihole01.wagsworld.com:192.168.200.9"
      - "pi501.wagsworld.com:192.168.1.9"
    environment:
      PRIMARY_HOST_BASE_URL: 'http://pihole01.wagsworld.com'
      PRIMARY_HOST_PASSWORD: '4AkRNelk'
      SECONDARY_HOSTS_1_BASE_URL: 'http://pi501.wagsworld.com'
      SECONDARY_HOSTS_1_PASSWORD: 'GFK7kec2xvu_xbg4pbz'
      #SECONDARY_HOSTS_2_BASE_URL: 'http://192.168.1.3'
      #SECONDARY_HOSTS_2_PASSWORD: 'your_password3'
      #SECONDARY_HOSTS_3_BASE_URL: 'http://server:8080'
      #SECONDARY_HOSTS_3_PASSWORD: 'your_password4'
      #SECONDARY_HOSTS_3_PATH: '/apps/pi-hole'
      INTERVAL_MINUTES: 5
      SYNC_V5_STATIC_DHCP_LEASES: 'true'
      TZ: 'America/New_York'
    restart: unless-stopped